# Generated by Django 5.2.4 on 2025-07-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('db_host', models.CharField(max_length=100)),
                ('db_port', models.CharField(max_length=10)),
                ('db_user_name', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=100)),
                ('db_database', models.CharField(max_length=100)),
                ('db_table_name', models.CharField(max_length=100)),
            ],
        ),
    ]
