# Generated by Django 5.2.4 on 2025-07-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbconfig',
            name='db_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
